// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrstructure.Data.Migrations
{
    [DbContext(typeof(WriteSysDbContext))]
    [Migration("20260421230956_AddPaytoHotel_Flight")]
    partial class AddPaytoHotel_Flight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("PostSequence");

            modelBuilder.HasSequence("TripSequence");

            modelBuilder.Entity("Domain.Entity.Amadeus.HotelSearchCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HotelSearchCaches");
                });

            modelBuilder.Entity("Domain.Entity.GenericDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.ToTable("GenericDiscounts");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CarbonEmissions")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightSearchHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("FlightSearchHistoryId1")
                        .HasColumnType("int");

                    b.Property<int>("Layovers")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlightSearchHistoryId");

                    b.HasIndex("FlightSearchHistoryId1");

                    b.ToTable("FlightOffers");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightSearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceInsightsId")
                        .HasColumnType("int");

                    b.Property<string>("SearchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PriceInsightsId");

                    b.ToTable("FlightSearchHistorys");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AirlineLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Airplane")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FlightOfferId")
                        .HasColumnType("int");

                    b.Property<int>("LegRoom")
                        .HasColumnType("int");

                    b.Property<bool>("Overnight")
                        .HasColumnType("bit");

                    b.Property<string>("TravelClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlightOfferId");

                    b.ToTable("FlightSegments", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EcoLabel")
                        .HasColumnType("int");

                    b.Property<int?>("HotelSearchHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NearbyPlaces")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<bool>("SponsoredHotel")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelSearchHistoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.HotelBrands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HotelBrandss");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.HotelLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HotelLocations");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.HotelSearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandsId");

                    b.ToTable("HotelSearchHistorys");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.PayFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightOfferId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalBookingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightOfferId");

                    b.HasIndex("UserId");

                    b.ToTable("PayFlights");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.PayHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalBookingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("payHotels");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.PriceInsights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PriceInsightss");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.RatePerNight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeforeTaxesFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Lowest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("RatePerNights");
                });

            modelBuilder.Entity("Domain.Entity.Identity.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Domain.Entity.Identity.Languages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Domain.Entity.Identity.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Domain.Entity.Identity.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasWhatsApp")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("Domain.Entity.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entity.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleName")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entity.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BlockedCounter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BlockedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BlockedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("FinancialBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Isverified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastOtpRequestTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextOtpAllowedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("OtpRequestCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Identity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.ExperiencePostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExperiencePostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExperiencePostId");

                    b.HasIndex("UserId");

                    b.ToTable("ExperiencePostComments");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.HiringPostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HiringPostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("Msg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HiringPostId");

                    b.HasIndex("UserId");

                    b.ToTable("HiringPostComments");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [PostSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entity.SpecificDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsage")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.HasIndex("TripId");

                    b.ToTable("SpecificDiscounts");
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuide", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BackIdentityPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontIdentityPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaryPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TourGuides", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuideAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TourGuideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourGuideId");

                    b.ToTable("TourGuideAddress", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuideBusinessGalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourGuidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourGuidId");

                    b.ToTable("TourGuideBusinessGalleries", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelCompany", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BackIdentityPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontIdentityPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TravelCompanies", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelCompanyBusinessGalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TravelCompanyId");

                    b.ToTable("TravelCompanyBusinessGalary", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelerCompanyAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TravelCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TravelCompanyId");

                    b.ToTable("TravelerCompanyAddress", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TravelerEntity.Traveler", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BackIdentityPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontIdentityPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Travelers", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TravelerEntity.TrvelerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TravelerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelerId");

                    b.ToTable("TravelerAddresses", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ActivityPrivateTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time");

                    b.Property<decimal>("FullPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PrivateTripId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TripCategory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrivateTripId");

                    b.ToTable("ActivityPrivateTrip", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ActivityPublicTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time");

                    b.Property<decimal>("FullPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PublicTripId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedDay")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TripCategory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublicTripId");

                    b.ToTable("ActivityPublicTrip", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.BookingPrivateTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AppProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightOffersId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("PrivateTripId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBookingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOwnerProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightOffersId");

                    b.HasIndex("HotelsId");

                    b.HasIndex("PrivateTripId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingPrivateTrips");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.BookingPublicTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AppProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightOffersId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("PublicTripId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBookingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOwnerProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightOffersId");

                    b.HasIndex("HotelsId");

                    b.HasIndex("PublicTripId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingPublicTrips");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.RequestTourGuidePrivateTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Accept")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrivateTripId")
                        .HasColumnType("int");

                    b.Property<int>("TourGuideId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrivateTripId");

                    b.HasIndex("TourGuideId");

                    b.ToTable("RequestTourGuidePrivateTrips");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.RequestTourGuidePulicTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Accept")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublicTripId")
                        .HasColumnType("int");

                    b.Property<int>("TourGuideId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublicTripId");

                    b.HasIndex("TourGuideId");

                    b.ToTable("RequestTourGuidePulicTrips");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrivateTripId1")
                        .HasColumnType("int");

                    b.Property<int?>("PublicTripId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrivateTripId1");

                    b.HasIndex("PublicTripId1");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Review");

                    b.HasDiscriminator().HasValue("Review");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [TripSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TripCategory")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.ExperiencePost", b =>
                {
                    b.HasBaseType("Domain.Entity.PostEntity.Post");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.HasIndex("CreatedById");

                    b.ToTable("ExperiencePosts");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.HiringPost", b =>
                {
                    b.HasBaseType("Domain.Entity.PostEntity.Post");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CreatedById");

                    b.ToTable("HiringPosts");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ReviewPrivateTrip", b =>
                {
                    b.HasBaseType("Domain.Entity.TripEntity.Review");

                    b.Property<int?>("PrivateTripId")
                        .HasColumnType("int");

                    b.HasIndex("PrivateTripId");

                    b.HasDiscriminator().HasValue("ReviewPrivateTrip");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ReviewPublicTrip", b =>
                {
                    b.HasBaseType("Domain.Entity.TripEntity.Review");

                    b.Property<int?>("PublicTripId")
                        .HasColumnType("int");

                    b.HasIndex("PublicTripId");

                    b.HasDiscriminator().HasValue("ReviewPublicTrip");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PrivateTrip", b =>
                {
                    b.HasBaseType("Domain.Entity.TripEntity.Trip");

                    b.Property<decimal?>("CustomizationFee")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TourGuideId")
                        .HasColumnType("int");

                    b.HasIndex("TourGuideId");

                    b.ToTable("PrivateTrips");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PublicTrip", b =>
                {
                    b.HasBaseType("Domain.Entity.TripEntity.Trip");

                    b.Property<int>("CurrentNumberOfMember")
                        .HasColumnType("int");

                    b.Property<int>("IncludedPackages")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumberOfMember")
                        .HasColumnType("int");

                    b.Property<decimal>("OwnerTripFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TourGuideId")
                        .HasColumnType("int");

                    b.Property<decimal>("TravelerFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("TourGuideId");

                    b.ToTable("PublicTrips");
                });

            modelBuilder.Entity("Domain.Entity.GenericDiscount", b =>
                {
                    b.HasOne("Domain.Entity.Identity.Admin", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightOffer", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.FlightSearchHistory", null)
                        .WithMany("BestFlights")
                        .HasForeignKey("FlightSearchHistoryId");

                    b.HasOne("Domain.Entity.Hotel_flights.FlightSearchHistory", null)
                        .WithMany("OtherFlights")
                        .HasForeignKey("FlightSearchHistoryId1");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightSearchHistory", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.PriceInsights", "PriceInsights")
                        .WithMany()
                        .HasForeignKey("PriceInsightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceInsights");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightSegment", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.FlightOffer", null)
                        .WithMany("Flights")
                        .HasForeignKey("FlightOfferId");

                    b.OwnsOne("Domain.Entity.Hotel_flights.AirportInfo", "ArrivalAirport", b1 =>
                        {
                            b1.Property<int>("FlightSegmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ArrivalAirportCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ArrivalAirportName");

                            b1.Property<DateTime>("Time")
                                .HasColumnType("datetime2")
                                .HasColumnName("ArrivalAirportTime");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("FlightSegmentId");

                            b1.ToTable("FlightSegments");

                            b1.WithOwner()
                                .HasForeignKey("FlightSegmentId");
                        });

                    b.OwnsOne("Domain.Entity.Hotel_flights.AirportInfo", "DepartureAirport", b1 =>
                        {
                            b1.Property<int>("FlightSegmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DepartureAirportCode");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DepartureAirportName");

                            b1.Property<DateTime>("Time")
                                .HasColumnType("datetime2")
                                .HasColumnName("DepartureAirportTime");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("FlightSegmentId");

                            b1.ToTable("FlightSegments");

                            b1.WithOwner()
                                .HasForeignKey("FlightSegmentId");
                        });

                    b.Navigation("ArrivalAirport")
                        .IsRequired();

                    b.Navigation("DepartureAirport")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.Hotel", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.HotelSearchHistory", null)
                        .WithMany("Hotels")
                        .HasForeignKey("HotelSearchHistoryId");

                    b.HasOne("Domain.Entity.Hotel_flights.HotelLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.HotelSearchHistory", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.HotelBrands", "Brands")
                        .WithMany()
                        .HasForeignKey("BrandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brands");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.PayFlight", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.FlightOffer", "FlightOffer")
                        .WithMany()
                        .HasForeignKey("FlightOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.PayHotel", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.RatePerNight", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.Hotel", null)
                        .WithMany("RatesPerNight")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("Domain.Entity.Identity.Admin", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("Domain.Entity.Identity.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Identity.Languages", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Identity.PhoneNumber", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany("phoneNumbers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Identity.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Identity.UserRole", b =>
                {
                    b.HasOne("Domain.Entity.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.ExperiencePostComment", b =>
                {
                    b.HasOne("Domain.Entity.PostEntity.ExperiencePost", "ExperiencePost")
                        .WithMany("Comments")
                        .HasForeignKey("ExperiencePostId");

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperiencePost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.HiringPostComment", b =>
                {
                    b.HasOne("Domain.Entity.PostEntity.HiringPost", "HiringPost")
                        .WithMany("Comments")
                        .HasForeignKey("HiringPostId");

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HiringPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.SpecificDiscount", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.TripEntity.PublicTrip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuide", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithOne("TourGuideProfile")
                        .HasForeignKey("Domain.Entity.TourGuidEntity.TourGuide", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuideAddress", b =>
                {
                    b.HasOne("Domain.Entity.TourGuidEntity.TourGuide", "TourGuide")
                        .WithMany("tourGuidAddresses")
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourGuide");
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuideBusinessGalary", b =>
                {
                    b.HasOne("Domain.Entity.TourGuidEntity.TourGuide", "TourGuid")
                        .WithMany("tourGuidBusinessGalaries")
                        .HasForeignKey("TourGuidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourGuid");
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelCompany", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithOne("TravelerCompanyProfile")
                        .HasForeignKey("Domain.Entity.TravelerCompanyEntity.TravelCompany", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelCompanyBusinessGalary", b =>
                {
                    b.HasOne("Domain.Entity.TravelerCompanyEntity.TravelCompany", "TravelCompany")
                        .WithMany("travelCompanyBusinessGalaries")
                        .HasForeignKey("TravelCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelCompany");
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelerCompanyAddress", b =>
                {
                    b.HasOne("Domain.Entity.TravelerCompanyEntity.TravelCompany", "TravelCompany")
                        .WithMany("traveleCompanyAddresses")
                        .HasForeignKey("TravelCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelCompany");
                });

            modelBuilder.Entity("Domain.Entity.TravelerEntity.Traveler", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithOne("TravelerProfile")
                        .HasForeignKey("Domain.Entity.TravelerEntity.Traveler", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.TravelerEntity.TrvelerAddress", b =>
                {
                    b.HasOne("Domain.Entity.TravelerEntity.Traveler", "Traveler")
                        .WithMany("trvelerAddresses")
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ActivityPrivateTrip", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PrivateTrip", "PrivateTrip")
                        .WithMany("PrivateActivities")
                        .HasForeignKey("PrivateTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateTrip");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ActivityPublicTrip", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PublicTrip", "PublicTrip")
                        .WithMany("PublicActivities")
                        .HasForeignKey("PublicTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicTrip");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.BookingPrivateTrip", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.FlightOffer", "FlightOffers")
                        .WithMany()
                        .HasForeignKey("FlightOffersId");

                    b.HasOne("Domain.Entity.Hotel_flights.Hotel", "Hotels")
                        .WithMany()
                        .HasForeignKey("HotelsId");

                    b.HasOne("Domain.Entity.TripEntity.PrivateTrip", "PrivateTrip")
                        .WithMany("BookingPrivateTrips")
                        .HasForeignKey("PrivateTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany("BookingPrivateTrips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightOffers");

                    b.Navigation("Hotels");

                    b.Navigation("PrivateTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.BookingPublicTrip", b =>
                {
                    b.HasOne("Domain.Entity.Hotel_flights.FlightOffer", "FlightOffers")
                        .WithMany()
                        .HasForeignKey("FlightOffersId");

                    b.HasOne("Domain.Entity.Hotel_flights.Hotel", "Hotels")
                        .WithMany()
                        .HasForeignKey("HotelsId");

                    b.HasOne("Domain.Entity.TripEntity.PublicTrip", "PublicTrip")
                        .WithMany("BookingPublicTrips")
                        .HasForeignKey("PublicTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Identity.User", "User")
                        .WithMany("BookingPublicTrips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightOffers");

                    b.Navigation("Hotels");

                    b.Navigation("PublicTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.RequestTourGuidePrivateTrip", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PrivateTrip", "PrivateTrip")
                        .WithMany("requestTourGuides")
                        .HasForeignKey("PrivateTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.TourGuidEntity.TourGuide", "TourGuide")
                        .WithMany()
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateTrip");

                    b.Navigation("TourGuide");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.RequestTourGuidePulicTrip", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PublicTrip", "PublicTrip")
                        .WithMany("requestTourGuides")
                        .HasForeignKey("PublicTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.TourGuidEntity.TourGuide", "TourGuide")
                        .WithMany()
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicTrip");

                    b.Navigation("TourGuide");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.Review", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PrivateTrip", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PrivateTripId1");

                    b.HasOne("Domain.Entity.TripEntity.PublicTrip", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PublicTripId1");

                    b.HasOne("Domain.Entity.Identity.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entity.Identity.User", "Reviewer")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.Trip", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "CreatedBy")
                        .WithMany("CreatedTrips")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.ExperiencePost", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.HiringPost", b =>
                {
                    b.HasOne("Domain.Entity.TravelerCompanyEntity.TravelCompany", "CreatedBy")
                        .WithMany("HiringPosts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ReviewPrivateTrip", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PrivateTrip", "PrivateTrip")
                        .WithMany()
                        .HasForeignKey("PrivateTripId");

                    b.Navigation("PrivateTrip");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.ReviewPublicTrip", b =>
                {
                    b.HasOne("Domain.Entity.TripEntity.PublicTrip", "PublicTrip")
                        .WithMany()
                        .HasForeignKey("PublicTripId");

                    b.Navigation("PublicTrip");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PrivateTrip", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "TourGuide")
                        .WithMany()
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TourGuide");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PublicTrip", b =>
                {
                    b.HasOne("Domain.Entity.Identity.User", "TourGuide")
                        .WithMany()
                        .HasForeignKey("TourGuideId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TourGuide");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightOffer", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.FlightSearchHistory", b =>
                {
                    b.Navigation("BestFlights");

                    b.Navigation("OtherFlights");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.Hotel", b =>
                {
                    b.Navigation("RatesPerNight");
                });

            modelBuilder.Entity("Domain.Entity.Hotel_flights.HotelSearchHistory", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("Domain.Entity.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entity.Identity.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("BookingPrivateTrips");

                    b.Navigation("BookingPublicTrips");

                    b.Navigation("CreatedTrips");

                    b.Navigation("Languages");

                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("Roles");

                    b.Navigation("TourGuideProfile");

                    b.Navigation("TravelerCompanyProfile");

                    b.Navigation("TravelerProfile");

                    b.Navigation("phoneNumbers");
                });

            modelBuilder.Entity("Domain.Entity.TourGuidEntity.TourGuide", b =>
                {
                    b.Navigation("tourGuidAddresses");

                    b.Navigation("tourGuidBusinessGalaries");
                });

            modelBuilder.Entity("Domain.Entity.TravelerCompanyEntity.TravelCompany", b =>
                {
                    b.Navigation("HiringPosts");

                    b.Navigation("travelCompanyBusinessGalaries");

                    b.Navigation("traveleCompanyAddresses");
                });

            modelBuilder.Entity("Domain.Entity.TravelerEntity.Traveler", b =>
                {
                    b.Navigation("trvelerAddresses");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.ExperiencePost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Entity.PostEntity.HiringPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PrivateTrip", b =>
                {
                    b.Navigation("BookingPrivateTrips");

                    b.Navigation("PrivateActivities");

                    b.Navigation("Reviews");

                    b.Navigation("requestTourGuides");
                });

            modelBuilder.Entity("Domain.Entity.TripEntity.PublicTrip", b =>
                {
                    b.Navigation("BookingPublicTrips");

                    b.Navigation("PublicActivities");

                    b.Navigation("Reviews");

                    b.Navigation("requestTourGuides");
                });
#pragma warning restore 612, 618
        }
    }
}
